<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Loan Balance Statement - {{ $loan->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #333; }
        .user-info { margin-bottom: 20px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table th { background-color: #f8f9fa; text-align: left; padding: 8px; border: 1px solid #ddd; }
        .table td { padding: 8px; border: 1px solid #ddd; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .text-primary { color: #6a3093; }
        .text-danger { color: #dc3545; }
        .text-success { color: #FFD700; }
        .summary { margin-top: 30px; padding-top: 15px; border-top: 1px dashed #333; }
        .footer { margin-top: 30px; font-size: 10px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Loan Balance Statement</h1>
        <p>Generated on: {{ $date }}</p>
    </div>

    <div class="user-info">
        <h3>Borrower Details</h3>
        <p><strong>Name:</strong> {{ $user->fname }} {{ $user->lname }}</p>
        <p><strong>Loan ID:</strong> {{ $loan->id }}</p>
        <p><strong>Loan Principal Amount :</strong> {{ number_format($loan->amount, 2, '.', ',') }}</p>
        <p><strong>Loan Payback Amount:</strong> {{ number_format(App\Models\Application::payback($loan->amount, $loan->repayment_plan, $loan->loan_product_id, $loan), 2, '.', ',') }}</p>
        <p><strong>Interest Rate:</strong> {{ $product->def_loan_interest }}%</p>
        <p><strong>Term:</strong> {{ $loan->repayment_plan }} months</p>
        <p><strong>Current Status:</strong>
            @if($loan->status == 0)
                Pending Review
            @elseif($loan->status == 1 )
                @if ($loan->closed == 1)
                    Closed
                @else
                    Open (Pending Repayment)
                @endif
            @elseif($loan->status == 2)
                Processing
            @elseif($loan->status == 3)
                Rejected
            @endif
        </p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Date</th>
                <th>Description</th>
                <th class="text-danger">Debit (Loan, Charges)</th>
                <th class="text-success">Credit (Payments)</th>
                <th>Balance</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($balance_statement as $key => $entry)
            <tr>
                <td>{{ $key + 1 }}</td>
                <td>{{ date('d M, Y', strtotime($entry->payment_date)) }}</td>
                <td>{{ $entry->description }}</td>
                <td class="text-danger">
                    {{ $entry->debit > 0 ? number_format($entry->debit, 2, '.', ',') : '-' }}
                </td>
                <td class="text-success">
                    {{ $entry->credit > 0 ? number_format($entry->credit, 2, '.', ',') : '-' }}
                </td>
                <td class="text-primary">
                    {{ number_format($entry->balance_after_payment, 2, '.', ',') }}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <table style="width: 100%">
            <tr>
                <td><strong>Total Loan Amount:</strong> {{ number_format($loan->amount, 2, '.', ',') }}</td>
                <td><strong>Total Paid:</strong> {{ number_format($total_paid, 2, '.', ',') }}</td>
                <td class="text-right"><strong>Outstanding Balance:</strong> {{ number_format($outstanding_balance, 2, '.', ',') }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} on {{ $date }}</p>
    </div>
</body>
</html>