<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Loan Repayment Schedule - {{ $loan->id }}</title>
    <style>
        body { font-family: DejaVu Sans, sans-serif; font-size: 12px; }
        .header { margin-bottom: 20px; border-bottom: 2px solid #333; padding-bottom: 10px; }
        .header h1 { margin: 0; color: #333; }
        .user-info { margin-bottom: 20px; }
        .table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
        .table th { background-color: #f8f9fa; text-align: left; padding: 8px; border: 1px solid #ddd; }
        .table td { padding: 8px; border: 1px solid #ddd; }
        .text-right { text-align: right; }
        .text-center { text-align: center; }
        .text-primary { color: #6a3093; }
        .text-danger { color: #dc3545; }
        .text-success { color: #FFD700; }
        .badge { padding: 3px 6px; border-radius: 3px; font-size: 11px; }
        .bg-success { background-color: #6a3093; color: white; }
        .bg-warning { background-color: #ffc107; color: black; }
        .bg-danger { background-color: #dc3545; color: white; }
        .summary { margin-top: 30px; padding-top: 15px; border-top: 1px dashed #333; }
        .footer { margin-top: 30px; font-size: 10px; text-align: center; }
    </style>
</head>
<body>
    <div class="header">
        <h1>Loan Repayment Schedule</h1>
        <p>Generated on: {{ $date }}</p>
    </div>

    <div class="user-info">
        <h3>Borrower Details</h3>
        <p><strong>Name:</strong> {{ $user->fname }} {{ $user->lname }}</p>
        <p><strong>Loan ID:</strong> {{ $loan->id }}</p>
        <p><strong>Loan Amount:</strong> {{ number_format($loan->amount, 2, '.', ',') }}</p>
        <p><strong>Interest Rate:</strong> {{ $product->def_loan_interest }}%</p>
        <p><strong>Term:</strong> {{ $loan->repayment_plan }} months</p>
    </div>

    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>Payment Date</th>
                <th>Installment Amount</th>
                <th>Principal</th>
                <th>Interest</th>
                <th>Remaining Balance</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody>
            @foreach ($repayment_schedule as $key => $installment)
            <tr>
                <td>{{ $key + 1 }}</td>
                <td>{{ \Carbon\Carbon::parse($installment->next_dates)->format('d M, Y') }}</td>
                <td class="text-primary">{{ number_format($installment->amount, 2, '.', ',') }}</td>
                <td>{{ number_format($installment->principal, 2, '.', ',') }}</td>
                <td>{{ number_format($installment->interest, 2, '.', ',') }}</td>
                <td class="text-danger">{{ number_format($installment->remaining_balance, 2, '.', ',') }}</td>
                <td>
                    @if ($installment->status == 'Paid')
                        <span class="badge bg-success">Paid</span>
                    @elseif ($installment->status == 'Pending')
                        <span class="badge bg-warning">Pending</span>
                    @elseif ($installment->status == 'Overdue')
                        <span class="badge bg-danger">Overdue</span>
                    @endif
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="summary">
        <table style="width: 100%">
            <tr>
                <td><strong>Total Paid:</strong> {{ number_format($total_paid, 2, '.', ',') }}</td>
                <td class="text-right"><strong>Remaining Balance:</strong> {{ number_format($remaining_balance, 2, '.', ',') }}</td>
            </tr>
        </table>
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} on {{ $date }}</p>
    </div>
</body>
</html>